* meeting notes April 6, 2025 
** the raku study group
**** usual links
***** these notes
****** https://github.com/doomvox/raku-study/blob/main/notes/meeting_2025apr06.org 

***** code examples
****** https://github.com/doomvox/raku-study/tree/main/bin/2025apr06
****** https://github.com/doomvox/raku-study/tree/main/bin/DeepMap

***** last meeting notes
****** https://github.com/doomvox/raku-study/blob/main/notes/meeting_2025mar09.org 

**** discussion group
***** https://github.com/doomvox/raku-study/discussions 

** topics
*** buffered io in perl and raku
**** example of processing subtitles files, *.srt
**** $OUTPUT_AUTOFLUSH, $|§
***** https://docs.raku.org/language/5to6-perlvar#$OUTPUT_AUTOFLUSH,_$|
#+BEGIN_SRC txt
No global alternative available. TTY handles are unbuffered by default, 
for others, set out-buffer to zero or use :!out-buffer with open on a specific IO::Handle.
#+END_SRC 
#+BEGIN_SRC raku
my $fh = 'foo'.IO.open: :w, :0out-buffer;
#+END_SRC 
***** TODO doc bug: unbuffered output not well covered in obvious places
****** https://docs.raku.org/language/io
****** https://docs.raku.org/type/IO/Handle#Buffering_terminals

*** neovim => lua; vim => perl
**** lua prototypal like JS
**** lua "table" is a hash/map/dictionary, not a "data frame"
*** zig community re-thought project design
**** no more make/autoconf etc.
*** makefile cultures 
*** jeff has a grammars question
**** parsing tokens run together, not separated by whitespace
***** jeff:
#+BEGIN_SRC txt
Tokens run together: 

FOOBAR#BAR"STRINGFOO"

The following are tokens:

- FOO
- BAR#
- BAR
- "STRINGFOO"

#+END_SRC 
***** TODO bruce gray has a solution (see saved chat)
#+BEGIN_SRC raku
    grammar G {
        regex TOP  { [ <foo> | <bar_hash> | <bar_plain> | <a_string> ]+ } # using `regex` where we would usually use `rule`
        token foo       { 'FOO'           }
        token bar_hash  { 'BAR#'          }
        token bar_plain { 'BAR'           }
        token a_string  { '"' <-["]>* '"' }
    }
    my $s = 'FOOBAR#BAR"STRINGFOO"';
    my $p = G.parse($s)
        orelse die;
    say $p;
  # Output:
  #     ｢FOOBAR#BAR"STRINGFOO"｣
  #      foo => ｢FOO｣
  #      bar_hash => ｢BAR#｣
  #      bar_plain => ｢BAR｣
  #      a_string => ｢"STRINGFOO"｣
#+END_SRC 

*** jeff has yet another question he's been too shy to tell us

*** marton raised a number of points in the group discussion
**** https://github.com/doomvox/raku-study/discussions
**** https://github.com/doomvox/raku-study/discussions/17
***** 
raku -e 'race for (^8).race(batch => 1, degree => 4) {sleep rand; .say}'
****** "race for" is at the very least not always faster then a bare "for"
****** "hyper for" is still another case

*** raku jvm backend discussion
**** it's an interpreter on top of an interpreter 
**** is it possible to write a compiler, to run raku on the jvm?
***** transpiler
***** marton: metamodel issues
****** "the six model"

*** rob: weirdness with whatever

*** rust
**** tim: readability issues
**** jeff: prefers finer control
**** marton: rust is C++ with half of it removed

*** tim refers to odd string reversal challenge
**** https://theweeklychallenge.org/blog/perl-weekly-challenge-313/
**** tim's solution in clojure
#+BEGIN_SRC lisp
```clj
(let [s "_c-!h_all-en!g_e"]
  (loop [chars (vec s) letters (filter alpha? chars) result ()]
    (if-let [ch (peek chars)]
      (if (alpha? ch)
        (recur (pop chars) (rest letters) (cons (first letters) result))
        (recur (pop chars) letters (cons ch result)))
      (str/join result))))
```
#+END_SRC 

**** bruce summarizes some raku solutions
#+BEGIN_SRC raku
# barroff
    my @characters = grep({ $_ ~~ m:i/ <[a..z]> / }, $str.comb);
    map({ $_ ~~ m:i/ <[a..z]> / ?? @characters.pop !! $_ }, $str.comb).join;
# feng-chang
    my @s = $s.comb;
    my @ndx = (^+@s).grep({ @s[$_] ~~ ('a'..'z')|('A'..'Z') });
    @s[@ndx] = @s[@ndx].reverse;
    put @s.join;
# jaldhar-h-vyas
    my @reversed = $str.comb.grep({ /<alpha>/ }).reverse;
    my $index = 0;
    ($str.subst(/<alpha>/, { @reversed[$index++] }, :g)).say;
# mark-anderson (similar to bruce's approach)
    my @s   = $str.comb;
    my @k   = @s.grep(/:i <[a..z]>/, :k);
    @s[@k] .= reverse;
    [~] @s
# wambash
    sprintf $str.trans( /<:alpha>/ => "%s"), $str.comb(/<:alpha>/).reverse
#+END_SRC 



** topics from Mar 9
*** jeff interested in how to create a new character encoding
**** roles?
**** utf8-c8
***** /home/doom/End/Cave/Raku/Wall/roast/S32-encoding/registry.t
***** https://github.com/rakudo/rakudo/issues/5807
***** TODO Add a problem-solving bug? Not clear how to do it.

*** rob: rakudo bug turned up in weekly challenge
**** .= operator not working as "explicit assignment"
**** https://github.com/rakudo/rakudo/issues/5803
#+BEGIN_SRC raku
## Example from the docs:
say ++$a.=abs;
say ++$a .= abs;  ## doesn't work
# Cannot modify an immutable Int (7)
#  in block <unit> at <unknown file> line 1

say ++$a.=abs;    ## this *does* work
# 8

## Marton's example
# -1.succ
# -2      ## the - is applied *after* the .succ increases value by 1

1.succ
# 2

-1 .succ  ## with the space, we start at -1 and step up 1 to 0
# 0
#+END_SRC raku

***** Marton looks up older reports:
****** https://github.com/rakudo/rakudo/issues/4996
****** https://github.com/rakudo/rakudo/issues/4863
****** https://github.com/Raku/doc/issues/3333

***** TODO Traps of .= weirdness not adequate
****** https://docs.raku.org/language/traps
******* https://docs.raku.org/language/traps#Method_calls_do_not_chain
******* https://docs.raku.org/language/traps#Method_operator_calls_and_prefix_minus

*** rob: raku base 36, bank echecks 
*** weekly challenge

*** jeff: cro experience

*** bike accident 

** follow-up 
*** announce next meeting immediately
*** check jeff's bug status
**** added pointer to roast test 
*** doc bug traps .= weirdness not well covered.

** announcements 
*** next meetings
**** Apr  6, 2025
***** after this, any two-week pattern crashes into Easter or Mother's Day
**** Apr 13, 2025
**** Apr 27, 2025
**** May 18, 2025

**** Perl & Raku Conference (Greenville, SC) 2025-06-27 through 29 Fri-Sun
***** https://tprc.us/

