* meeting notes Jan 31, 2021
** agenda
*** hello, welcome (pretend you're a warm human being)
*** announcements  
**** svperl talk on regexes: https://www.meetup.com/SVPerl/events/fftdcsyccdbgb/
planning on following with a pack/unpack talk 
(what would Raku equivalent be?)
*** invite suggested topics
*** work on topics
*** today's code examples:
https://github.com/doomvox/raku-study/tree/main/bin/2021jan31
https://github.com/doomvox/raku-study/blob/main/bin/richard_hainsworth_role_class.pm6

** possible topics
*** Q: somewhere in the docs there's a good simple grammar example parsing ini-style format data
*** lambert lum: problem with recursive regexes
*** sigils in raku: you can stash anything in a $ so what does it mean?
**** related to "containers"?
**** also twigils
*** regexes and grammars again
**** get a handle on basics
***** Note: initial grammar tutorial example in docs is too complex, focuses on proto and inheritence
https://docs.raku.org/language/grammar_tutorial
***** Follow Moritz Lenz?
**** simple parsing job: doomfiles
*** regexes
**** csv example: show difference of zero-width comma matching vs literal
**** play with %
*** string interpolation: "\s" is an error.  
Should it be " "? Note that "\n" and "\t" work.
*** Code by Richard Hainsworth (finanalyst): "The repeated code is irritating me."
https://github.com/doomvox/raku-study/commit/891a2e1b643b3c56f86d44ce91c5016e065c06c3

