* meeting notes February 9, 2025

** the raku study group
**** usual links
***** these notes
****** https://github.com/doomvox/raku-study/blob/main/notes/meeting_2025feb09.org 

***** code examples
****** https://github.com/doomvox/raku-study/tree/main/bin/2025feb09

***** last meeting notes
****** https://github.com/doomvox/raku-study/blob/main/notes/meeting_2025jan26.org

** apologies
*** I wonder how this meeting went-- I couldn't make it 
*** As I was trying to get into the meeting, Zoom insisted I upgrade first
*** Ten minutes later I was back in the meeting, with audio only working
*** Everything else, including my entire desktop, got frozen by trying to use Zoom.
*** I tried some simple things like a full reboot, but no luck
*** I took a guess that it was time to upgrade Debian
**** the zoom app claims it works with Debian versions 10 or greater
**** I was on 11 (bullseye), but was aware it was stale now that 12 was out (bookworm)
***** the full upgrade proceedure took even longer than I expected: completed after midnight.
***** (I think I may go back to wiping the disk and doing fresh installs-- isn't it faster?)
***** But I wasn't going to do a dist upgrade without a backup-- that burned a few hours, too
***** Not to mention reading the release notes for bookworm and such
***** Then I had the fun of sorting through the quasi-breakage the new Debian inflicted on me
****** Briefly: I ended up with the gdm3 login manager (btw: I call the "dm" the dungeon master)
****** This appears to *default* to wayland, which you can change only by editing a configuration file
****** gdm3 advertises it has features to let you choose a session type, e.g. a window manager: this is now more-or-less a lie.
****** experimented with installing different dungeon masters, eventually settingly on wdm
******* I also tried "update-alternatives --config x-window-manager": doesn't seem to help at all
******* I can now get into my favorite window manager (icewm), but it's not reading settings right
******** neither background color or theme works (or for that matter, the background image)
******** have to manually re-enable the Infadel2 theme to get the bright white background to go away
****** beginning to wonder about Debian-- do they have to swill down anything gnome/Redhat shoves in their mouth?

** topics
*** (moved to next meeting)

** old topics, last meeting
*** deepmap internals
**** bruce gray examines the hash.new.STORE issue
***** /home/doom/End/Cave/RakuStudy/Wall/raku-study/t/Deepmap/hash_new_store_uneven_lists.raku
***** Note: STORE is from Associative *conceptually*, but for odd reasons (bootstrapping) it's included in the Hash code

*** Rob: some context where using an array gives you first value, not say, count, or whole array
**** actually: case where an array just has one element, slips the element out and treats it as the one item
***** TODO that sounds like "the single argument rule" in for loops

*** Bruce Gray found issue with handling of first element in produce/triangle operation
**** turned up in working the weekly challenge
***** definitly a trap-- maybe a bug
***** 
#+BEGIN_SRC raku
@numbers = 1, 2, 3;
say [\~]  @numbers;
## you get strings output, *except* for the first element, that stays a number:
##   1, '12', '123'
#+END_SRC 

***** marton argues this is a bug
****** ~ has a single argument version, so why not handle first element correctly?
#+BEGIN_SRC sh
raku -e 'say .WHAT for &infix:<~>(5)'
(Str)
#+END_SRC
****** notably: reduce doesn't show this bug, just produce does

*** weekly challenge 305
**** rob question about series of three triple dot ranges
**** bg steps through task 1, leading up to using produce/triangle bug

*** Marton: another "pair destructuring" issue was opened:
**** https://github.com/rakudo/rakudo/issues/5718
***** https://github.com/doomvox/raku-study/discussions/6
**** https://github.com/rakudo/rakudo/issues/4534

*** TODO for next meeting:
**** https://github.com/doomvox/raku-study/discussions/7

*** lizmat, finding code that isn't executed
**** https://dev.to/lizmat/finding-the-coverables-3l13

** follow-up 
*** deepmap core code
**** TODO followup: try out my proposed fix for deepmap bug
*** TODO add some material here using screenshots from
**** /home/doom/End/Cave/RakuStudy/Notes/2026jan26
*** TODO post two week advance notice meeting annoucement


** announcements 
*** next meetings
**** Feb  9, 2025
**** Feb 23, 2025
**** Mar  9, 2025
**** Mar 23, 2025
**** Apr  6, 2025
***** after this, the two-week pattern crashes into Easter: stay tuned

*** Perl & Raku Conference (Greenville, SC) 2025-06-27 through 29 Fri-Sun
**** https://news.perlfoundation.org/post/dates_set_tprc_2025
**** https://tprc.us/
**** REOPENED TALK SUBMISSION 
***** New Deadline: March 1


