* meeting notes Mar 07, 2021


** announcments
*** richard hainsworth: alternative pod6 processing 
**** His version of Raku docs: http://raku.finanalyst.org

** the usual meeting links:
*** https://github.com/doomvox/raku-study/tree/main/bin/2021mar07
*** https://github.com/doomvox/raku-study/blob/main/notes/meeting_2021mar07.md
*** SF Perl site for mailing list subscription info:
**** http://sf.pm.org/

** "topics" (disorganized list of stuff I'm pretending belongs in a hierarchy)

*** back to last weeks regex problem, munging sudoers lines via a sysadmin tool
**** problem posed by lambert lum, who revealed his solution
***** $line =~ s{(^Defaults\s+secure_path\s*(?:.(?!/usr/local/bin))*$)}{$1:/usr/local/bin};
**** yary approach, with some doomvox additons:
***** https://github.com/doomvox/raku-study/blob/main/bin/2021feb28/pcre_regex_to_append_path_non_redundantly.t
***** "\K" regex code is Trick #7: https://blogs.oracle.com/linux/the-top-10-tricks-of-perl-one-liners-v2
***** Bruce Gray confirms "PCRE does understand \K"
**** david christensen variation, showed a scripted solution
***** virtue of handling cases like escaped continuation lines with trailing comments
**** raku translation-- still has problems
***** https://github.com/doomvox/raku-study/blob/main/bin/2021feb28/regex_append_to_sudoers_line.raku

*** jeff had questions about compiler options, etc
**** --cc=$(tc=getCC)
***** Bruce Gray points at:
****** https://github.com/MoarVM/MoarVM/blob/master/Configure.pl
******* --moar-option='--option=value'
Options to pass to MoarVM configuration for --gen-moar
******* 

*** William Michels suggests doing this simple shell problem in Raku:
**** https://unix.stackexchange.com/a/636948
**** there were a few interesting angles involving with raku character classes
https://github.com/doomvox/raku-study/blob/main/bin/2021mar07/strip_control_chars_from_utf8.pl6
**** 

** linux kernel module to shut up damn bell

** bash books, much new features
*** bash          (d christensen pick)
*** bash cookbook (d christensen mention, weak writing)
*** unix shells (jeff pick)
*** "pro bash programming" by chris johnson, apress (alan pick)

*** book on the hidden logic of english:
**** "uncovering the logic of english" (jeff pick)
***** clusters of morphemes

*** humble bundle promotion: oreilley pocket references

*** bruce gray discussion
**** http://rosettacode.org/wiki/Modified_random_distribution#Raku

*** shadow novel where esperanto was spoken
***  "Crime Under Cover" (1941) by Maxwell Grant
****  http://obsidianrook.com/doomfiles/LA_OMBRO.html

*** misc elements from chat

**** William Michels : August 26, 2019 "Lenovo Security Flaw Could Affect Millions: What to Do Now" 
***** https://www.laptopmag.com/articles/lenovo-solution-center-vulnerability




15:08:19	 From Bill Michels : "Cc"	"Control" or "cntrl" on this page: https://docs.raku.org/language/regexes#Unicode_properties
15:10:06	 From Bruce Gray : Better: https://docs.raku.org/language/regexes#Predefined_character_classes
15:11:53	 From Bill Michels : https://tools.ietf.org/html/rfc3629#section-3
15:12:54	 From Bruce Gray : raku -e 'say (^256).grep({ .chr ~~ /<cntrl>/ }).fmt("%x")'
0 1 2 3 4 5 6 7 8 9 a b c d e f 10 11 12 13 14 15 16 17 18 19 1a 1b 1c 1d 1e 1f 7f 80 81 82 83 84 85 86 87 88 89 8a 8b 8c 8d 8e 8f 90 91 92 93 94 95 96 97 98 99 9a 9b 9c 9d 9e 9f
15:13:02	 From Jeff : https://raku-musings.com/rash1.html
15:14:13	 From Bruce Gray : collapses to 0x00..0x1f, 0x7f, 0x80..0x9f
15:15:00	 From Joseph Brenner : https://github.com/doomvox/raku-study/tree/main/bin/2021mar07
15:15:19	 From Joseph Brenner : https://github.com/doomvox/raku-study/blob/main/notes/meeting_2021mar07.md
15:16:09	 From Bruce Gray : https://en.wikipedia.org/wiki/Control_character#In_Unicode
15:16:14	 From Bruce Gray : https://en.wikipedia.org/wiki/Unicode_control_characters
15:19:52	 From Jeff : #rmod pcspkr#vi /etc/modprobe.d/blacklistblacklist pcspkr:wq
15:26:14	 From Bruce Gray : http://redsymbol.net/articles/unofficial-bash-strict-mode/
https://olivergondza.github.io/2019/10/01/bash-strict-mode.html
15:26:25	 From Jeff : yes, good article!
15:27:56	 From Jeff : zsh
15:31:51	 From Bill Michels : ~$ raku
Welcome to ð‘ðšð¤ð®ðð¨â„¢ v2020.10.
Implementing the ð‘ðšð¤ð®â„¢ programming language v6.d.
Built on MoarVM version 2020.10.

To exit type 'exit' or '^D'
> say $/ if "hello\n" ~~ / <:Ll>+<:Cc>+ /;
ï½¢hello
ï½£
> say $/ if "hello\n" ~~ / <:Ll>+ /;
ï½¢helloï½£
> say $/ if "hello\n" ~~ / <:Cc>+ /;
ï½¢
ï½£
>
15:35:03	 From Jeff : 0xfffe
15:35:47	 From Jeff : err... 0xfffd
15:37:08	 From Bill Michels : https://util.unicode.org/UnicodeJsps/character.jsp?a=FFFD
15:39:14	 From Jeff : tr [[:ctrl:]]
15:39:27	 From Bill Michels : "3.7 Enabling Lossless Conversion" https://www.unicode.org/reports/tr36/#EnablingLosslessConversion
15:40:43	 From Bruce Gray : Bill: variant:
15:40:45	 From Bruce Gray : raku -e 'say $/ if "hello\n" ~~ $_ for /<.lower>+<.cntrl>+/, /<.lower>+/, /<.cntrl>+/;'
15:42:12	 From Bruce Gray : <:Ll>+<:Cc>+
15:43:36	 From Bruce Gray : <:Ll+:Cc>
15:44:14	 From Bill Michels : > say $/ if "hello\n" ~~ / <:Cc>+<:Ll>+ /;
()
>
15:44:54	 From Bill Michels : YES!!
15:44:56	 From Bill Michels : > say $/ if "hello\n" ~~ / <:Cc+:Ll>+ /;
ï½¢hello
ï½£
>
15:45:03	 From Bill Michels : Thanks Bruce!
15:45:14	 From Bruce Gray : yw
15:47:56	 From Bruce Gray : Alternate: <:lower+:cntrl>
15:48:50	 From Bill Michels : <[<:Cc+:Ll> #]>+
15:51:58	 From Jeff : print
15:51:59	 From Jeff : print#
15:55:38	 From Bruce Gray : raku -e 'say $/ if "hello\n" ~~ $_ for /<:lower+:cntrl>+/, /<.lower>+/, /<.cntrl>+/;'
16:02:47	 From Bruce Gray : http://rosettacode.org/wiki/Modified_random_distribution#Raku
16:04:21	 From Jeff : wu
16:10:20	 From Bill Michels : https://www.humblebundle.com/books/pocket-reference-guides-oreilly-books
16:12:13	 From Joseph Brenner : http://perl-begin.org/humour/perl6_perl_6_cover_lg.jpg
16:23:35	 From Joseph Brenner : To really nerd out, we need to start talking about loglan or lojban.
16:23:45	 From Joseph Brenner : (And I'll invariably bring up Babel-17).
17:06:41	 From Bruce Gray : https://en.wikipedia.org/wiki/The_World_of_Null-A
17:09:18	 From Joseph Brenner : categories
17:09:20	 From Joseph Brenner : organon
17:09:22	 From Joseph Brenner : aristotle

** possible topics (not covered this time)

*** andrew shitov's raku course on-line:
https://course.raku.org/

*** the great "say Set.^methods" affair
**** the issue (bug report and discussion):
https://github.com/rakudo/rakudo/issues/4207

**** the roast test, aka the spec:
https://github.com/Raku/roast/blob/master/S12-introspection/methods.t
***** it checks the case of inheritence, but not roles

*** a stupid mistake that isn't: naming a method with a leading ^
**** https://stackoverflow.com/questions/54143036/class-method-name-with-doesnt-get-invoked-properly/54147131#54147131
***** should this generate a warning/error?
*** 69 cent tour of raku regexs
*** some simple grammar demos

** more possible topics (carried over from earlier meetings)
*** Steven_lembark
**** https://www.slideshare.net/lembark/hypers-and-gathers-and-takes-oh-my
***** slide21:  "unit sub MAIN { ..."  unit?
**** https://www.slideshare.net/lembark/generating-querying-calendar-tables-in-posgresql
*** adverbs that control returns, e.g. :p for pairs (a feature Bruce Gray likes)
**** https://docs.raku.org/language/subscripts#index-entry-:p_(subscript_adverb)
*** andrew shitov "Perl 6 at a Glance"
**** https://andrewshitov.com/perl6-at-a-glance/
**** https://andrewshitov.com/wp-content/uploads/2020/01/Perl-6-at-a-Glance.pdf
*** perl weekly challenge: 
**** https://perlweeklychallenge.org/

*** promises and threads
**** https://www.reddit.com/r/rakulang/comments/lthpxe/are_promises_multithreaded/
**** Jonathan Worthington
***** https://github.com/Raku/CCR/blob/main/Remaster/Jonathan%20Worthington/Racing-to-writeness-to-wrongness-leads.md
***** https://github.com/Raku/CCR/blob/main/Remaster/Jonathan%20Worthington/A-unified-and-improved-Supply-concurrency-model.md
