* meeting notes August 29, 2021
** hidden agenda
*** TODO 
** before I forget
*** the argument to round might be called "nearest"
"round off to the nearest"

** multiple dispatch

Larry Wall on Raku:

"We don't actually have types for the benefit of strong typing.
That's third place.  Second place is we can optimize better.  But
first place is actually it's there for multiple dispatch."

   -- Erlang & Elixir Factory, 2017

Douglas Crockford:

"But it turns out that strong typing does not eliminate the
need for careful testing.  And I have found in my work that the
sorts of errors that strong type checking finds are not the
errors I worry about."  

   -- "Javascript: The Good Parts" (2008)

*** standard complaint
**** we could check whether strong typing helps
***** e.g. conduct experiments where teams of programmers compete
***** but computer "scientists" don't do experiments
****** not if it means consulting wtih a social scienctist
***** unverified claims about human cognitive abilities abound
