* meeting notes May 16, 2021
** agenda stuff
*** writing grep variants
**** my first attempt: /home/doom/End/Cave/DoomfileTools/bin/df_grep.raku
*** raku classes as data containers
**** https://github.com/doomvox/raku-study/tree/main/bin/2021apr25/data_container_class.raku

*** bruce gray rosettacode entries
**** http://rosettacode.org/wiki/Barnsley_fern#Raku 
**** http://rosettacode.org/wiki/Coprime_triplets#Raku
**** https://rosettacode.org/wiki/Tree_from_nesting_levels#Raku 

*** argument passing signatures
**** /home/doom/End/Cave/Ice/Xtal/Perl6/passing_args.org
**** /home/doom/End/Cave/Perl6/Wall/raku-study/bin/2021may02/mixing_named_args_and_positional_ones.raku

*** super flat
**** https://stackoverflow.com/questions/67515479/what-is-a-simple-and-elegant-way-to-flatten-lists-or-arrays-of-arbitrary-depths
**** https://stackoverflow.com/questions/41648119/how-can-i-completely-flatten-a-list-of-lists-of-lists
**** https://en.wikipedia.org/wiki/Superflat
**** a job for flat?
***** https://stackoverflow.com/questions/67373726/why-are-empty-raku-shaped-arrays-truthy
"As a follow up, I wonder if a good way to test 'all elements are undefined' is @shaped-array.any.so ???"

*** type system: what is accepted by what  
**** is anything ever cast automatically
***** when can you Cool

*** david christensen talked about a few debian sysadmin issues
**** summary: debian 10.9 is mature enough to deal with all display hardware, 
including nvidia optimus
***** bruce gray recommends "bumblebee" to deal with nvidia optimus
https://wiki.debian.org/Bumblebee 
**** rough notes from david's piece:
dell two slots 4gb, certain dells have quiet motherboard
upgrades, two 8gb, 16gb, dual channel memory.  good for
virtualization.  SSD sata drive bay (sata two or three?)
nvidia optimus (two graphics spliced together) 
debian version 7 wouldn't boot, video issues.  eventually fixed.
put win7 pro on it for awhile, support yanked 1.5 
new used laptop win10
debian 10 was n.g. same video problem
debian 9 needed some point revisions to get there 
interested in debian 10, may have it fixed
(Note: I've got debian 10.9 slated to install).
intel model 520 ssds  enterprise desktop drive, sata 3,
self-encrypting (?), on linux uses dm-crypt for swap, nbr
partitioning, not gpt.  1gig unencrypted boot partition.
overprovisioning, a couple of different devices-- image on usb
flash drive.

samsung gb ssd performed better than usb drives, dram cache
burn up a sata slot.

*** higher-order programming as a substitute for macros (perl5)  (david christensen)
As a demo of functional programming, david christensen showed us
his code for generating type validation predicate functions
("is_string", etc). 

**** other approaches
***** bruce gray suggests Params::Util
***** https://metacpan.org/pod/Params::Util
***** there are a number of cpan modules to do parameter validation, e.g 
****** https://metacpan.org/pod/Type::Tiny#Predicate-methods
****** https://metacpan.org/pod/Params::ValidationCompiler
***** a package I wrote that does something similar
****** https://metacpan.org/pod/Scalar::Classify
******* comparing david's code to mine:
******** david's is certainly tighter, and is very consistent
******** mine does fewer sub calls-- probably performs better
******** mine returns an expanded set of string codes like the built-in "ref"
********* need to do string comparisons later might seem inelegant

*** william michels asks about one-liners to strip "soft hypens"
**** none of us had ever *seen* a soft hyphen before:
## 00AD;SOFT HYPHEN;Cf;0;BN;;;;;N;;;;;
**** what they do makes some sense: 
they mark a point in a word where it's okay to hyphenate, but
when there's no need to hyphenate, they become invisible
zero-width markers
*** bill found them in this page, notably written by hyphenation nerds:
https://practicaltypography.com/hyphenation.html
**** example
Hy­phen­ation is the au­to­mated process of break­ing words be­tween lines to cre­ate more con­sis­tency across a text block.
*** William Michels : Q. Should Raku create pre-defined (so-called) "Grey-space" character classes?
*** bruce gray supplies some requested one-liners:
**** raku -e 'say .trans("\c[SOFT HYPHEN]" => "") for lines()'
**** raku -e 'say .trans("\c[SOFT HYPHEN]" => "").chars for lines();'
*** he also makes the point you can do a chained operation to strip whitespace as well
**** raku -e 'say .trans("\c[SOFT HYPHEN]" => "").trans("\s" => "").chars for lines();' 
*** raku also lets you define custom character classes extending pre-defined ones
#+BEGIN_SRC perl6
# strip soft hyphens (U+00AD) as well as whitespace (\s)
$text_no_gs ~~ s:g/<[\s\x[00ad]]>//;
#+END_SRC

** ongoing
*** programming in the large (david christensen)
**** larger applications
**** raku die handlers
*** raku idioms
**** https://github.com/doomvox/raku-study/blob/main/notes/idioms.org
***** https://gfldex.wordpress.com/2021/04/16/all-your-idioms-are-belong-to-us/
***** maybe: favor methods over functions?

** appendix: the usual links
*** code examples
https://github.com/doomvox/raku-study/tree/main/bin/2021may16
*** meeting notes (material from this file)
https://github.com/doomvox/raku-study/tree/main/notes/meeting_2021may16.md
*** SF Perl page, has links to mailing list
http://sf.pm.org/
*** perl6-users mailing list archive
https://www.nntp.perl.org/group/perl.perl6.users/

** bits

*** bg summarizes
fosdem codesection langs for opensource  corporate backed typescript go java
raku optimized in other ways

*** announced: going to skip next sunday, thinking about going with every-other week format
suggestion: have someone else host perl5 meetings on the
off-weeks.  david christensen is interested. 

*** perl5 cpan module  Filesys::ZFS, david christensen says "not complete"

*** there's a raku documentation mailing list, created by lizmat
**** Richard Hainsworth : documentation@raku.org
**** don't know how to subscribe, or if it's archived somewhere

https://github.com/Raku/Raku-Steering-Council/blob/main/announcements/20200720.md

*** steve yegge, a fascinating perl hater:
https://steve-yegge.blogspot.com/
