* meeting notes Feb 14, 2021
** agenda
*** welcome
*** any announcements?
**** sv perl talk, "secure coding in perl", Thursday, March 04, 6:39pm
https://www.meetup.com/SVPerl/events/gjdzdsyccfbgb/
*** any suggested topics?
** meeting links
The meeting notes (this file):
https://github.com/doomvox/raku-study/blob/main/notes/meeting_2021feb14.org
Demo scripts:
https://github.com/doomvox/raku-study/tree/main/bin/2021feb14
** possible topics
*** in raku, data objects are faster than hashes (a lizmat point)
*** classes vs prototypes: toddandmargo vs ralph mellor
https://www.nntp.perl.org/group/perl.perl6.users/2021/02/msg9706.html
*** sets/bags/mixes 
**** could use a general name.  Larry Wall called them QuantHashes
**** some Set methods
***** elems
***** grab
***** grabpairs
***** maxpairs
***** minpairs
***** pick
weighted random pick
***** pickpairs
***** of
***** roll
like pick, but can use with Mix too (pick not a Mix method, eh?)
**** convenience issues
I rate convenience over performance on these features.
Why doesn't this work?

#+BEGIN_SRC perl6
my $result = set @monster2  (-) set @monsters1;
# Variable '@monster2' is not declared.  Did you mean any of these:
# '@monsters2', '@monsters1'?
#+END_SRC

See:
https://github.com/doomvox/raku-study/tree/main/bin/2021feb14/sets_etc-vot_lizmat_2020.pl6



*** Kernighan on raku
**** Brian Kernighan on Perl6 (Raku): https://youtu.be/Sg4U4r_AgJU?t=3429 
**** new book "unix a memoir and a history"
** lambert lum asks about pack/unpack: just in experimental form in raku
https://docs.raku.org/routine/unpack

** MONKEY-PATCHING, augment
https://docs.raku.org/syntax/augment
https://docs.raku.org/language/experimental#macros 
https://docs.raku.org/language/pragmas#nqp 

** jonathan swift, etc
http://obsidianrook.com/doomfiles/MODEST_PROPOSAL.html

** misc subjects, smalltalk and beyond
*** squeak
https://squeak.org/ 

*** seaside
https://en.wikipedia.org/wiki/Seaside_(software)
https://github.com/seasidest/seaside 

*** flow-based programming book
j. paul morrison (70s)

*** oslo perl mongers 
brian d foy 
renaming raku worked

** brian d foy, preparing for perl 7
https://leanpub.com/preparing_for_perl7/c/oslo 

