* meeting notes February 26, 2023
** the raku study group
**** usual links
***** these notes
****** https://github.com/doomvox/raku-study/blob/main/notes/meeting_2023feb26.md
****** source file (for corrections, etc)
******* https://github.com/doomvox/raku-study/blob/main/notes/meeting_2023feb26.org
***** code examples
****** https://github.com/doomvox/raku-study/tree/main/bin/2023feb26
***** last meeting notes
****** https://github.com/doomvox/raku-study/blob/main/notes/meeting_2022feb12.md


** topics

*** the ever popular weekly challenge
***** https://theweeklychallenge.org/blog/perl-weekly-challenge-201/
***** https://theweeklychallenge.org/blog/perl-weekly-challenge-202/


https://theweeklychallenge.org/blog/perl-weekly-challenge-205/

 TASK #1: Third Highest

You are given an array of integers. Write a script to find out the Third Highest if found otherwise return the maximum.

TASK #2: Maximum XOR

You are given an array of integers. Write a script to find the highest value obtained by XORing any two distinct members of the array.

https://theweeklychallenge.org/blog/perl-weekly-challenge-204/

Task 1: Monotonic Array
Submitted by: Mohammad S Anwar
You are given an array of integers.

Write a script to find out if the given array is Monotonic. Print 1 if it is otherwise 0.

Task 2: Reshape Matrix
Submitted by: Mohammad S Anwar

You are given a matrix (m x n) and two integers (r) and (c).

Write a script to reshape the given matrix in form (r x c) with the original value in the given matrix. If you can’t reshape print 0.


*** being a better raku citizen
**** lizmat reminds she needs advance notice of meeting schedule for 
**** do we need a joint events calendar?
**** irc 
**** vadim class
**** marton meetings on docs
***** first one was yesterday
***** squashathon
****** https://github.com/2colours/Raku-ideas/blob/main/Squashathon%20reborn.md

*** jj merelo raku recipies code examples
**** https://github.com/Apress/raku-recipes


** announcements 
*** next meeting: February 26th
*** doc meeting:  jit.sy issues?  
